export interface SummaryDTO {
  AISummaryID: string;
  "UserID(FK)": string;
  "MemoID(FK)": string[];
  "TagID(FK)": string[];
  content: string;
  createdDate: string;
  updatedDate: string;
  isAutoGenerated: boolean;
}
